sudo: required
services:
    - docker

before_install:
    - docker build -t angelo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run angelo/react-test npm test -- --coverage

after_success:
    - docker build -t angelo/multi-client ./client
    - docker build -t angelo/multi-nginx ./nginx
    - docker build -t angelo/multi-server ./server
    - docker build -t angelo/multi-worker ./worker
    #log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker-hub
    - docker push angelo/multi-client
    - docker push angelo/multi-nginx
    - docker push angelo/multi-server
    - docker push angelo/multi-worker